---
- name: Add user ziutus with ssh keys
  hosts: all
  become: true
  tasks:
    - name: Add user ziutus
      user:
        name: ziutus
        state: present
        shell: /bin/bash

    - name: Add ssh keys
      authorized_key:
        user: ziutus
        key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILEEUnYKCshJ01MYKaCMXcE53z0VZWIB6qGBS4yCuuHS lenie-default"
        state: present

    - name: Add user maciek
      user:
        name: maciek
        state: present
        shell: /bin/bash
