# StatefulSet dla PGVector
apiVersion: apps/v1
kind: StatefulSet  # StatefulSet jest lepszy dla baz danych niż Deployment
metadata:
  name: pgvector
  namespace: lenie-ai-dev
spec:
  serviceName: pgvector
  replicas: 1
  selector:
    matchLabels:
      app: pgvector
  template:
    metadata:
      labels:
        app: pgvector
    spec:
      containers:
      - name: pgvector
        image: pgvector/pgvector:0.8.0-pg17  # Dokładnie ten obraz, który chcesz użyć
        ports:
        - containerPort: 5432
          name: postgres
        env:
        - name: POSTGRES_DB
          value: vectordb
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: pgvector-secrets  # Należy utworzyć ten Secret
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pgvector-secrets  # Należy utworzyć ten Secret
              key: password
        volumeMounts:
        - name: pgvector-storage
          mountPath: /var/lib/postgresql/data
          subPath: pgdata  # Używamy subPath, aby uniknąć problemów z uprawnieniami
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "800m"
      volumes:
      - name: pgvector-storage
        persistentVolumeClaim:
          claimName: pgvector-pvc
