---
# Secret dla danych uwierzytelniających (wykonaj osobno)
# kubectl create secret generic pgvector-secrets \
#   --from-literal=username=pguser \
#   --from-literal=password=twoje-haslo \
#   --namespace=lenie-ai-dev
apiVersion: v1
kind: Secret
metadata:
  name: pgvector-secrets
  namespace: lenie-ai-dev
type: Opaque
data:
  # Te wartości są zakodowane w base64, należy je zmienić na właściwe
  username: cGd1c2Vy  # base64 dla "pguser"
  password: dHdvamUtaGFzbG8=  # base64 dla "twoje-haslo"
