repos:
  - repo: local
    hooks:
      - id: trufflehog
        name: TruffleHog
        description: Detect secrets in your data.
        language: docker_image
        entry: 'docker run --rm -it -v "${PWD}:/pwd" trufflesecurity/trufflehog git file://. --only-verified --fail --since-commit HEAD'
        stages: ["pre-commit", "pre-push"]
