#repos:
#  - repo: local
#    hooks:
#      - id: trufflehog
#        name: TruffleHog
#        description: Detect secrets in your data.
#        entry: 'docker run --rm -it -v "${PWD}:/pwd" trufflesecurity/trufflehog git file://. --only-verified --fail --since-commit HEAD'
#        language: system
#        stages: ["pre-commit", "pre-push"]
