name: lenie-ai

services:
  lenie-ai-server:
    build: ./backend
    ports:
      - "5000:5000"
    restart: unless-stopped
    depends_on:
      - lenie-ai-db
    env_file: .env
  lenie-ai-db:
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - lenie-ai-db-data:/var/lib/postgresql/data
      - ./backend/database/init:/docker-entrypoint-initdb.d
    restart: unless-stopped
  lenie-ai-fronted:
    build: ./web_interface_react
    ports:
      - "3000:3000"
    restart: unless-stopped

volumes:
  lenie-ai-db-data:
    driver: local
networks:
  default:
    driver: bridge
