version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1


jobs:
  start-ec2:
    docker:
      - image: cimg/python:3.11
    steps:
      - aws-cli/setup
      - run:
          name: "Start EC2 instances"
          command: |
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set region $AWS_REGION            
            aws ec2 wait start-instances --instance-ids $INSTANCE_ID

  run-job-on-ec2:
    machine: true
    resource_class: itsnap/itsnap-runner
    steps:
      - checkout
      - run:
          name: "Execute job on EC2"
          command: |
            ls -l


  stop-ec2:
    docker:
      - image: cimg/python:3.11
    steps:
      - aws-cli/setup
      - run:
          name: "Start EC2 instances"
          command: |
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set region $AWS_REGION            
            aws ec2 stop-instances --instance-ids $INSTANCE_ID

workflows:
  ec2-workflow:
    jobs:
      - start-ec2
      - run-job-on-ec2:
          requires:
            - start-ec2
      - stop-ec2:
          requires:
            - run-job-on-ec2
