version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1


jobs:
  start-ec2:
    docker:
      - image: cimg/python:3.11
    steps:
      - aws-cli/setup
      - run:
          name: "Start EC2 instances"
          command: |
            aws ec2 start-instances --instance-ids $INSTANCE_ID

  run-job-on-ec2:
    machine: true
    resource_class: itsnap/itsnap-runner
    steps:
      - checkout
      - run:
          name: "Execute job on EC2"
          command: |
            ls -l
      - run:
          name: "Tworzenie wirtualnego środowiska Python 3.11"
          command: |
            python3.11 -m venv venv
            . venv/bin/activate

            # Sprawdzenie, czy venv jest aktywny
            echo "Sprawdzanie aktywacji wirtualnego środowiska:"
            echo "VIRTUAL_ENV=$VIRTUAL_ENV"
            which python
            python -c "import sys; print(f'Interpreter Pythona: {sys.executable}')"
            python -c "import sys; print(f'Ścieżki systemowe: {sys.path}')"
                        
            python -m pip install --upgrade pip
            pip install -r requirements_server.txt || echo "No requirements_server.txt file found"
            echo "Wirtualne środowisko Python 3.11 utworzone i aktywowane"
            python --version
            python -m pytest --self-contained-html --html=pytest-results/ || true
  

  stop-ec2:
    docker:
      - image: cimg/python:3.11
    steps:
      - aws-cli/setup
      - run:
          name: "Start EC2 instances"
          command: |     
            aws ec2 stop-instances --instance-ids $INSTANCE_ID

workflows:
  ec2-workflow:
    jobs:
      - start-ec2
      - run-job-on-ec2:
          requires:
            - start-ec2
      - stop-ec2:
          requires:
            - run-job-on-ec2
