AWSTemplateFormatVersion: '2010-09-09'
Description: 'API Gateway for Lenie main application'

Parameters:
  stage:
    Default: dev
    Description: Specify stage (dev, qas, prd)
    Type: String
    AllowedValues:
      - dev
      - qas
      - prd

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaBasicExecution2
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"

  LenieRdsStartFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: !Sub lenie-${stage}-rds-start
      Handler: 'lambda_function.lambda_handler'
      Role: !GetAtt LambdaExecutionRole.Arn
      LoggingConfig:
        LogFormat: 'JSON'
        ApplicationLogLevel: 'INFO'
        SystemLogLevel: 'INFO'
      Code:
        S3Bucket: !Sub '{{resolve:ssm:/lenie/${stage}/s3/cloudformation/name}}'
        S3Key: !Sub lenie-${stage}-rds-start.zip
      Runtime: !Sub '{{resolve:ssm:/lenie/${stage}/python/lambda-runtime-version}}'
      Timeout: 30
      MemorySize: 128
      Environment:
        Variables:
          LOG_LEVEL: 'INFO'
          DB_ID: !Sub '{{resolve:ssm:/lenie/${stage}/database/name}}'




  LenieApi:
    Type: 'AWS::ApiGateway::RestApi'
    Properties:
      Name: 'lenie_dev_split'
      Description: 'API for Chrome extension "Lenie AI assistant"'
      EndpointConfiguration:
        Types:
          - REGIONAL
      Body:
        openapi: "3.0.1"
        info:
          title: !Sub "lenie_${stage}_split"
          description: "API for \"Lenie AI assistant\""
          version: "2025-02-21T10:52:31Z"
        paths:
          /database/start:
            post:
              responses:
                "200":
                  description: "200 response"
                  content:
                    application/json:
                      schema:
                        $ref: "#/components/schemas/Empty"
              security:
                - api_key: []
              x-amazon-apigateway-integration:
                type: "aws_proxy"
                httpMethod: "POST"
                uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:lenie-${stage}-rds-start/invocations"
                passthroughBehavior: "when_no_match"
                timeoutInMillis: 29000
                contentHandling: "CONVERT_TO_TEXT"
            options:
              responses:
                "200":
                  description: "200 response"
                  headers:
                    Access-Control-Allow-Origin:
                      schema:
                        type: "string"
                    Access-Control-Allow-Methods:
                      schema:
                        type: "string"
                    Access-Control-Allow-Headers:
                      schema:
                        type: "string"
                  content: {}
              x-amazon-apigateway-integration:
                type: "mock"
                responses:
                  default:
                    statusCode: "200"
                    responseParameters:
                      method.response.header.Access-Control-Allow-Methods: "'DELETE,GET,HEAD,OPTIONS,PATCH,POST,PUT'"
                      method.response.header.Access-Control-Allow-Headers: "'Content-Type,Authorization,X-Amz-Date,X-Api-Key,X-Amz-Security-Token'"
                      method.response.header.Access-Control-Allow-Origin: "'*'"
                requestTemplates:
                  application/json: '{"statusCode": 200}'
                passthroughBehavior: "when_no_match"
        components:
          schemas:
            Empty:
              title: "Empty Schema"
              type: "object"
          securitySchemes:
            api_key:
              type: "apiKey"
              name: "x-api-key"
              in: "header"


  ApiStage:
    Type: 'AWS::ApiGateway::Stage'
    Properties:
      DeploymentId: !Ref ApiDeployment
      RestApiId: !Ref LenieApi
      StageName: 'v1'

  ApiDeployment:
    Type: 'AWS::ApiGateway::Deployment'
#    DependsOn:
#      - UrlAddMethod
#      - UrlAddOptionsMethod
    Properties:
      RestApiId: !Ref LenieApi

  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref LenieRdsStartFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${LenieApi}/*/*"
