Resources:
  MyLambdaFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Role: arn:aws:iam::234876388473:role/service-role/lenie_2_db-role-ulzrajys
      Code:
        S3Bucket: my-example-bucket
        S3Key: my-example-app.zip
      Runtime: nodejs12.x
      Timeout: 10