Metadata:
  License: Apache-2.0
AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS S3 for cloudformation code for Lenie application'

Parameters:
  ProjectName:
    Type: String
    Description: 'Project Name'
  Environment:
    Type: String
    Description: 'environment'

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${ProjectName}-2025-${Environment}-cloudformation

  CloudFormationSSMParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub '/lenie/${Environment}/s3/cloudformation/name'
      Type: String
      Value: !Sub ${ProjectName}-2025-${Environment}-cloudformation
      Description: 'Bucket for cloudformation code'
