AWSTemplateFormatVersion: '2010-09-09'
Resources:
  BlackAllScpPolicy:
    Type: 'AWS::Organizations::Policy'
    Properties:
      Content: |
        {
            "Version": "2012-10-17",
            "Statement": [
                {
                    "Sid": "DenyMemberAccountInstances",
                    "Effect": "Deny",
                    "Action": [
                        "sso:CreateInstance"
                    ],
                    "Resource": "*"
                }
            ]
        }
      Description: "Deny Creation of SSO"
      Name: "BlockSSOCreation"
      Type: "SERVICE_CONTROL_POLICY"

