AWSTemplateFormatVersion: '2010-09-09'
Description: Test template for security groups

Resources:
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access from specific IP address
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 31.183.191.172/32
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 31.183.191.173/32