AWSTemplateFormatVersion: '2010-09-09'
Description: Template to create a Passwords etc for Lenie application

Parameters:
  Environment:
    Description: The stage of the application deployment
    Default: dev
    Type: String
    AllowedValues:
      - dev
      - qa
      - prod
      - cob
      - test
      - feature
  ProjectName:
    Type: String
    Description: 'Project Name'
  DBMasterUserPassword:
    Type: String
    Description: 'RDS Master User Password'
    NoEcho: true # Opcjonalnie, aby ukryć hasło

Resources:
  RDSPasswordSecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Sub '/${ProjectName}/${Environment}/rds/password'
      Description: 'Secret that holds the RDS master user password'
      SecretString: !Sub |
        {
          "username": "lenie",
          "password": "${DBMasterUserPassword}"
        }