apiVersion: v1
kind: Pod
metadata:
  name: lenie-ai-server
  namespace: lenie-ai-dev
spec:
  containers:
  - name: lenie-ai-server
    image: linuxexpertpl/lenie-ai-server:0.2.9
    ports:
    - containerPort: 5000
    envFrom:
    - configMapRef:
        name: env-config
    - secretRef:
        name: env-secret
        