apiVersion: v1
kind: Service
metadata:
  name: lenie-ai-server-service
  namespace: lenie-ai-dev
spec:
  selector:
    app: lenie-ai-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
  