apiVersion: v1
kind: Pod
metadata:
  name: postgres-4-1
spec:
  securityContext:
    runAsNonRoot: true
  containers:
    - name: postgres
      securityContext:
        allowPrivilegeEscalation: false
      image: docker.io/postgres:15-bullseye
      env:
        - name: POSTGRES_PASSWORD
          value: P4ssw0rd!
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
      volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: dbdata
  volumes:
    - name: dbdata
      persistentVolumeClaim:
        claimName: dbvol